version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
      - image: "ubuntu-1604:202004-01"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing Boost
          command: 'apt-get install -y libboost-all-dev'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Creating Debug Build Folder
          command: 'mkdir debug'
      - run:
          name: Running CMAKE
          command: 'cd debug && cmake -DCMAKE_BUILD_TYPE=Debug ..'
      - run:
          name: Running MAKE
          command: 'cd debug && make VERBOSE=1'
      - run:
          name: Unit Tests (Debug)
          command: 'cd debug && ./tests'
      - run:
          name: Creating Release Build Folder
          command: 'mkdir release'
      - run:
          name: Running CMAKE
          command: 'cd release && cmake -DCMAKE_BUILD_TYPE=Release ..'
      - run:
          name: Running MAKE
          command: 'cd release && make VERBOSE=1'
      - run:
          name: Unit Tests (Release)
          command: 'cd debug && ./tests'

