version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Creating Build Folder
          command: 'mkdir build && cd build'
      - run:
          name: Running CMAKE
          command: 'cd build && cmake ..'
      - run:
          name: Running MAKE
          command: 'make build'
      - run:
          name: Unit Tests
          command: './build/tests'
